/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id.ac.uniska.pbo2.p03.komponen.gui;

/**
 *
 * @author amell
 */

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.FlatLightLaf;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
public class FormPendaftaran extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormPendaftaran.class.getName());

    /**
     * Creates new form FormPendaftaran
     */
    public FormPendaftaran() {
        initComponents();
        
        // Kode tambahan ditulis di sini
        namaField.putClientProperty("JTextField.placeholderText", "Nama lengkap");
        npmField.putClientProperty("JTextField.placeholderText", "Contoh: 2410010001");
        getRootPane().setDefaultButton(daftarButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jeniskelaminGroup = new javax.swing.ButtonGroup();
        namaLabel = new javax.swing.JLabel();
        npmLabel = new javax.swing.JLabel();
        prodiLabel = new javax.swing.JLabel();
        jeniskelaminLabel = new javax.swing.JLabel();
        minatLabel = new javax.swing.JLabel();
        namaField = new javax.swing.JTextField();
        npmField = new javax.swing.JTextField();
        prodiCombo = new javax.swing.JComboBox<>();
        lakiRadio = new javax.swing.JRadioButton();
        perempuanRadio = new javax.swing.JRadioButton();
        javaCheck = new javax.swing.JCheckBox();
        pythonCheck = new javax.swing.JCheckBox();
        webCheck = new javax.swing.JCheckBox();
        temaToggle = new javax.swing.JToggleButton();
        daftarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pendaftaran Workshop");

        namaLabel.setText("Nama");

        npmLabel.setText("NPM");

        prodiLabel.setText("Program Studi");

        jeniskelaminLabel.setText("Jenis Kelamin");

        minatLabel.setText("Minat");

        prodiCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Teknik Informatika", "Sistem Informasi", "Manajemen Informasi" }));

        lakiRadio.setText("Laki-laki");

        perempuanRadio.setText("Perempuan");

        javaCheck.setText("Java");

        pythonCheck.setText("Python");

        webCheck.setText("Web");

        temaToggle.setText("Mode Gelap");
        temaToggle.addActionListener(this::temaToggleActionPerformed);

        daftarButton.setText("Daftar");
        daftarButton.addActionListener(this::daftarButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(npmLabel)
                            .addComponent(prodiLabel)
                            .addComponent(jeniskelaminLabel)
                            .addComponent(namaLabel))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lakiRadio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(perempuanRadio))
                            .addComponent(namaField)
                            .addComponent(npmField)
                            .addComponent(prodiCombo, 0, 220, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(temaToggle)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(minatLabel)
                                .addGap(73, 73, 73)
                                .addComponent(javaCheck)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pythonCheck)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(webCheck))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                .addComponent(daftarButton)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaLabel)
                    .addComponent(namaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npmLabel)
                    .addComponent(npmField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prodiCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(prodiLabel)
                        .addGap(7, 7, 7)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jeniskelaminLabel)
                    .addComponent(lakiRadio)
                    .addComponent(perempuanRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minatLabel)
                    .addComponent(javaCheck)
                    .addComponent(pythonCheck)
                    .addComponent(webCheck))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(temaToggle)
                    .addComponent(daftarButton))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void daftarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarButtonActionPerformed
        tampilkanRingkasan();
    }//GEN-LAST:event_daftarButtonActionPerformed

    private void temaToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temaToggleActionPerformed
        gantiTema(temaToggle.isSelected());
    }//GEN-LAST:event_temaToggleActionPerformed
    
   private void tampilkanRingkasan() {
    String jenisKelamin = lakiRadio.isSelected() ? "Laki-laki" : "Perempuan";
    
    List<String> minat = new ArrayList<>();
    for (JCheckBox cb : List.of(javaCheck, pythonCheck, webCheck)) {
        if (cb.isSelected()) {
            minat.add(cb.getText());
        }
    }
    
    String pesan = "Nama: " + namaField.getText()
            + "\nNPM: " + npmField.getText()
            + "\nProgram Studi: " + prodiCombo.getSelectedItem()
            + "\nJenis Kelamin: " + jenisKelamin
            + "\nMinat: " + (minat.isEmpty() ? "-" : String.join(", ", minat));
            
    JOptionPane.showMessageDialog(this, pesan, "Data Pendaftaran", JOptionPane.INFORMATION_MESSAGE);
}

private void gantiTema(boolean gelap) {
    if (gelap) {
        FlatDarkLaf.setup();
    } else {
        FlatLightLaf.setup();
    }
    FlatLaf.updateUI();
    temaToggle.setText(gelap ? "Mode Terang" : "Mode Gelap");
}

public static void main(String args[]) {
    FlatLightLaf.setup();
    java.awt.EventQueue.invokeLater(() -> new FormPendaftaran().setVisible(true));
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton daftarButton;
    private javax.swing.JCheckBox javaCheck;
    private javax.swing.ButtonGroup jeniskelaminGroup;
    private javax.swing.JLabel jeniskelaminLabel;
    private javax.swing.JRadioButton lakiRadio;
    private javax.swing.JLabel minatLabel;
    private javax.swing.JTextField namaField;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JTextField npmField;
    private javax.swing.JLabel npmLabel;
    private javax.swing.JRadioButton perempuanRadio;
    private javax.swing.JComboBox<String> prodiCombo;
    private javax.swing.JLabel prodiLabel;
    private javax.swing.JCheckBox pythonCheck;
    private javax.swing.JToggleButton temaToggle;
    private javax.swing.JCheckBox webCheck;
    // End of variables declaration//GEN-END:variables
}
